"""Build a standalone HTML report from actual saved study inputs and status."""
import csv
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if (ROOT / 'results/assumption-screening/results.json').exists():
    import runpy
    runpy.run_path(str(ROOT / 'scripts/build_screening_report.py'), run_name='__main__')
    raise SystemExit(0)
def esc(value):
    return html.escape(str(value))
def read_csv(name):
    with (ROOT / 'data' / name).open(encoding='utf-8', newline='') as stream:
        return list(csv.DictReader(stream))
bom = read_csv('bom.csv')
matches = read_csv('dataset_matching.csv')
status = json.loads((ROOT / 'results/status.json').read_text())
validation = json.loads((ROOT / 'results/validation.json').read_text())
manifest = json.loads((ROOT / 'data/source_manifest.json').read_text())
assert len(bom) == 12 and abs(sum(float(x['mass_g']) for x in bom) - 860.8) < 1e-6
assert status['gwp100_kg_co2_eq'] is None, 'Update report wording if actual impact results become available'
known = sum(float(x['finished_mass_g']) for x in matches if x['dataset_id'])
rows = ''.join(f'<tr><td>{esc(r["material_name"])}</td><td>{float(r["mass_g"]):g}</td><td>{float(r["mass_g"])/1000:g}</td><td>{"포장" if r["group"] == "packaging" else "제품"}</td></tr>' for r in bom)
bars = ''.join(f'<div class="bar-row"><span>{esc(r["material_name"])}</span><div class="track"><div style="width:{float(r["mass_g"])/350.25*100:.2f}%"></div></div><b>{float(r["mass_g"]):g} g</b></div>' for r in sorted(bom, key=lambda x:float(x['mass_g']), reverse=True))
match_rows = ''.join('<tr>'+''.join(f'<td>{esc(v)}</td>' for v in [r['material_name'],r['database'] or '미확보',r['dataset_name'] or '적합한 공정 미확보',r['dataset_id'] or '—',r['dataset_version'] or '—',r['geography'] or '—',r['reference_year'] or '—',f"{r['reference_amount']} {r['reference_unit']}" if r['dataset_id'] else '—','인벤토리 확보 · 매칭 검토 필요' if r['dataset_id'] else '미확보'])+'</tr>' for r in matches)
decisions = ''.join(f'<details><summary>{esc(r["material_name"])}</summary><p>{esc(r["selection_rationale"])}</p>'+ (f'<p><a href="{esc(r["source_url"])}">공식 원본 다운로드 / 데이터셋 출처</a></p><p>SHA-256: <code>{esc(r["sha256"])}</code></p>' if r['source_url'] else '<p>검색한 공개 스냅샷에서 적합한 공정을 확보하지 못했습니다. 현재 플랫폼 전체에 없다는 뜻은 아닙니다.</p>')+'</details>' for r in matches)
source_rows = ''.join(f'<tr><td>TianGong {esc(k)}</td><td><a href="{esc(v["url"])}/tree/{esc(v["commit"])}">고정 커밋 원본</a></td><td><code>{esc(v["commit"])}</code></td></tr>' for k,v in manifest['repositories'].items())
content = f'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>BC1 1 L 전기주전자 LCA 결과 보고서</title>
<style>
:root{{--ink:#192d3b;--muted:#526776;--line:#dce5eb;--accent:#176f78;--bg:#f2f6f8}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.7 system-ui,-apple-system,"Malgun Gothic",sans-serif}}main{{max-width:1120px;margin:40px auto;padding:0 24px 40px}}header{{padding:32px;background:#163a47;color:white;border-radius:18px}}h1{{font-size:30px;line-height:1.35;margin:10px 0}}h2{{font-size:22px;margin-top:0}}h3{{font-size:18px}}.eyebrow{{font-size:13px;letter-spacing:.08em}}section{{background:white;border:1px solid var(--line);border-radius:14px;padding:26px;margin-top:22px}}.notice{{background:#fff6e6;border-left:5px solid #d59a2a;padding:18px;margin-top:20px}}.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:20px}}.card{{background:white;border:1px solid var(--line);padding:18px;border-radius:12px}}.card strong{{display:block;font-size:25px}}.card span,.muted{{color:var(--muted);font-size:14px}}table{{border-collapse:collapse;width:100%;font-size:14px}}th,td{{padding:10px 12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{background:#edf4f6}}.scroll{{overflow:auto}}a{{color:var(--accent)}}code{{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}}.bar-row{{display:grid;grid-template-columns:220px 1fr 80px;gap:12px;align-items:center;font-size:14px;margin:9px 0}}.track{{background:#e9f1f3;border-radius:4px;overflow:hidden}}.track div{{height:15px;background:var(--accent)}}details{{border-top:1px solid var(--line);padding:12px 0}}summary{{cursor:pointer;font-weight:600}}.formula{{font:22px ui-monospace,monospace;background:#edf4f6;padding:18px;border-radius:8px}}footer{{font-size:13px;color:var(--muted);margin-top:22px}}@media(max-width:700px){{main{{margin-top:16px;padding:0 12px}}.cards{{grid-template-columns:repeat(2,1fr)}}.bar-row{{grid-template-columns:130px 1fr 65px;font-size:12px}}h1{{font-size:24px}}section{{padding:18px}}}}@media print{{body{{background:white}}main{{max-width:none;margin:0;padding:0}}header{{background:white;color:var(--ink);border:1px solid var(--line)}}section,.card{{break-inside:avoid}}.scroll{{overflow:visible}}table{{font-size:10px}}details{{display:block}}}}
</style></head><body><main>
<header><div class="eyebrow">LIFE CYCLE ASSESSMENT · BC1 · 2026-10-08</div><h1>1 L 플라스틱 전기주전자<br>전과정평가 결과 보고서</h1><p>선언단위: 제조·포장을 마친 전기주전자 1개, 공장 출하 단계</p></header>
<div class="notice"><strong>현재 상태: 실제 환경영향평가 결과 미계산</strong><br>BOM과 데이터 접근, 행렬 계산 코드는 검증했습니다. 하지만 전체 공급망·제조 입력·특성화 연결이 완성되지 않아 실제 주전자의 s, g, h 및 환경영향 총량을 계산하지 못했습니다. 이 보고서는 확인된 결과와 남은 공백을 제시하며, 미계산 값을 0으로 표시하지 않습니다.</div>
<div class="cards"><div class="card"><strong>860.8 g</strong><span>제품 + 포장 총질량</span></div><div class="card"><strong>12개</strong><span>BOM 재료</span></div><div class="card"><strong>7 / 12</strong><span>실제 인벤토리 후보 확보</span></div><div class="card"><strong>15 / 15</strong><span>합성 알고리즘·BOM 테스트 통과</span></div></div>
<section><h2>1. 연구 목적과 시스템 경계</h2><p>원료 생산, 부품 가공, 조립 및 제조, 포장 생산을 포함하는 공장 출하까지의 분석입니다. 소비자 사용과 제품 폐기 단계는 제외합니다. 제조 중 발생하는 스크랩 처리 여부는 별도 검토가 필요합니다. 공장 위치, 평가 기준연도, 정격출력과 소재 등급은 확인되지 않았습니다.</p><p>목적은 TianGong과 USLCI의 실제 자료를 기반으로 공급망 인벤토리와 환경영향을 계산하는 것입니다. 제품 간 비교, 시나리오 및 불확실성 분석은 수행하지 않았습니다.</p></section>
<section><h2>2. BOM 검증 결과</h2><p><strong>제품 723 g + 포장 137.8 g = 총 860.8 g.</strong> 사용자 제공 CSV의 12개 재료를 확인했습니다. g → kg 변환은 1,000으로 나눕니다. 완제품 질량이므로 구매 투입량과 같다고 가정하지 않았습니다.</p><div class="scroll"><table><thead><tr><th>재료</th><th>질량 g</th><th>질량 kg</th><th>구분</th></tr></thead><tbody>{rows}</tbody></table></div><h3>재료별 질량 분포</h3><p class="muted">아래 그래프는 질량 비교이며 환경영향 기여도 그래프가 아닙니다.</p>{bars}</section>
<section><h2>3. 실제 데이터 확보와 매칭</h2><p>TianGong 역사적 ILCD 스냅샷: <strong>4,132개 공정</strong>. USLCI 1.2025-06.0 JSON-LD: <strong>962개 공정</strong>. USLCI FY19.Q2.01 ILCD: <strong>758개 공정</strong>. 다운로드 파일의 해시와 USLCI ZIP 무결성을 확인했습니다. 최신 데이터와 역사적 데이터는 구분했습니다.</p><p>후보 인벤토리를 확보한 재료의 질량은 {known:g} g입니다. 이는 후보 데이터의 질량 범위이지, 환경영향 또는 전체 공급망의 확보율이 아닙니다. 확보된 7개 후보도 소재·지역·가공 적합성 검토와 공급자 연결이 필요합니다.</p><div class="scroll"><table><thead><tr><th>재료</th><th>DB</th><th>공정 후보</th><th>UUID</th><th>버전</th><th>지역</th><th>연도/기간</th><th>기준량·단위</th><th>상태</th></tr></thead><tbody>{match_rows}</tbody></table></div><h3>선정 근거·대체 데이터 검토</h3>{decisions}</section>
<section><h2>4. Three Matrix Operations</h2><div class="formula">A s = f &nbsp; → &nbsp; g = B s &nbsp; → &nbsp; h = C g</div><p><strong>A:</strong> 기준 제품을 행, 공정을 열로 둔 기술권 행렬. 각 공정을 기준 생산량으로 정규화하고 공급자 투입을 연결합니다. SciPy <code>spsolve(A, f)</code>로 활동량 s를 구하며 역행렬을 직접 만들지 않습니다.</p><p><strong>B:</strong> 같은 공정 열에 대응하는 기본흐름 투입·배출 행렬. UUID·버전·단위·방향·구획을 보존합니다. g는 전체 전과정목록입니다.</p><p><strong>C:</strong> 검증된 영향평가 방법의 특성화 인자 행렬. 기본흐름과 정확히 연결한 뒤 h를 계산합니다. 누락된 인자를 임의로 0으로 두지 않습니다.</p><p>단일 기준산출의 귀속적 모델을 지원하도록 구현했습니다. 다중산출 할당, 재활용·스크랩 크레딧, 바이오제닉 탄소는 미확정입니다. PP 성형 공정에 이미 포함된 수지나 골판지 변환 공정을 다시 더하면 이중 계산이 되므로 확인해야 합니다.</p></section>
<section><h2>5. 환경영향 결과와 검증 구분</h2><table><thead><tr><th>항목</th><th>결과</th><th>의미</th></tr></thead><tbody><tr><td>실제 주전자 활동량 s</td><td>미계산</td><td>완전한 공정 네트워크 미확보</td></tr><tr><td>실제 주전자 인벤토리 g</td><td>미계산</td><td>전체 공급자 연결 미완성</td></tr><tr><td>실제 주전자 영향평가 h</td><td>미계산</td><td>검증된 인벤토리·특성화 연결 부족</td></tr><tr><td>GWP100, kg CO₂-eq/주전자</td><td>미계산</td><td>0이 아니라 결과 없음</td></tr><tr><td>환경영향 기여도·상위 3개 재료</td><td>미계산</td><td>질량만으로 영향 순위를 판단하지 않음</td></tr><tr><td>BOM 개수·질량·단위 변환</td><td>통과</td><td>실제 첨부 BOM 검증</td></tr><tr><td>알고리즘 및 입력 검증 테스트</td><td>15개 통과</td><td>합성 테스트; 주전자 환경영향 검증 아님</td></tr></tbody></table><p>실제 주전자의 행렬 잔차, 특성화 범위, 기여도 합계 및 이중 계산 검증은 아직 수행하지 못했습니다. 불확실성 구간과 민감도 결과도 미계산입니다.</p></section>
<section><h2>6. 미완료 원인과 필요한 입력</h2><ul><li>황동, 등급이 지정되지 않은 나일론, POM, PC, 경화 실리콘의 적합한 공정 인벤토리.</li><li>제조 수율·손실, 성형·가공 서비스, 스크랩 처리 및 조립 전력.</li><li>확보한 후보의 배경 공급자 연결과 외부 의존성.</li><li>영향평가 방법과 기본흐름의 단위·구획·버전 연결. TianGong 기후 방법에는 IPCC 2021/2013 출처 표기가 함께 있어 검토가 필요합니다.</li></ul><p>과제 사이트, TianGong 플랫폼, LCA Commons와 Box 경로는 이 환경의 네트워크 프록시에서 403으로 차단되었습니다. 공개 GitHub 역사적 데이터는 내려받았습니다. 최신 플랫폼 Export 또는 허용된 완전한 데이터 파일과 제조 입력이 확보돼야 분석을 이어갈 수 있습니다.</p></section>
<section><h2>7. 출처와 재현 방법</h2><p>연구일: 2026-10-08. Python {esc(validation['python'])}, NumPy {esc(validation['numpy'])}, SciPy {esc(validation['scipy'])}. 분석 파일과 코드: <a href="https://github.com/jiyeong1219/jy">GitHub 프로젝트</a>.</p><p>저장소에서 <code>pip install -r requirements.txt</code>, <code>python -m unittest discover -s tests -v</code>, <code>python scripts/workflow.py status</code>를 실행합니다. 마지막 명령은 미완료 상태를 알리는 종료코드 2를 반환합니다. 이 HTML은 <code>python scripts/build_report.py</code>로 다시 생성합니다.</p><div class="scroll"><table><thead><tr><th>공식 저장소</th><th>출처</th><th>고정 커밋</th></tr></thead><tbody>{source_rows}</tbody></table></div><p>USLCI 배포 안내: <a href="https://github.com/FLCAC-admin/uslci-content/blob/dev/docs/release_info/release-downloads.md">공식 다운로드 목록</a>. 실제 배포 버전·파일 해시·접근 절차는 프로젝트의 <code>data/source_manifest.json</code>과 <code>docs/DATABASE_ACCESS.md</code>에 기록되어 있습니다.</p><p>Codex가 데이터 조사, 코드·보고서 작성을 수행했습니다. 사용자가 경계, 공식 출처와 BOM을 제공했습니다. 독립적 사람의 최종 매칭 승인은 기록되지 않았습니다. 이 분석은 첫 준비 실행이며, 완성된 기준 영향값이나 수정 전후 영향값은 없습니다.</p></section>
<footer>독립 실행 식별자: {esc(status['run_id'])} · 외부 CSS/스크립트 없이 열리는 단일 HTML · 숫자를 추정해 채운 환경영향 결과는 없습니다.</footer>
</main></body></html>'''
output = ROOT / 'results/report.html'
output.write_text(content, encoding='utf-8')
print(f'Created {output} ({output.stat().st_size} bytes)')
